blog/urls.py
from django.urls import path

from .views import index, post, create

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('post/<int:pk>', post, name='post'),
    path('create/', create, name='create'),
]

demo/urls.py
from django.urls import path

from .views import index, create, details, delete, edit

app_name = 'demo'

urlpatterns = [
    path("", index, name='index'),
    path("create/", create, name='create'),
    path("details/<int:pk>/", details, name='details'),
    path("edit/<int:pk>/", edit, name='edit'),
    path("delete/<int:pk>/", delete, name='delete'),
]

lesson08/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('demo.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True)
    post = models.ForeignKey('Post', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.text[:20]


class Post(models.Model):
    title = models.CharField(max_length=100, blank=False)
    content = models.TextField()
    draft = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tag)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-updated']

demo/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']


class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_of_date = models.DateField()
    courses = models.ManyToManyField(Course)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

demo/forms.py
from django import forms

from demo.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        # fields = '__all__'
        # fields = ('first_name', 'last_name')
        exclude = ('created', 'updated')
        widgets = {
            'birth_of_date': forms.DateInput(attrs={'type': 'date'})
        }

blog/views.py
from django.db.models import Q
from django.shortcuts import render

from .forms import PostForm
from .models import Post


def index(request):
    q = request.GET.get('q')
    if q:
        posts = Post.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
    else:
        posts = Post.objects.all()
    return render(request, 'blog/index.html',
                  context={'posts': posts, 'q': q})


def post(request, pk):
    return render(request, 'blog/post.html')


def create(request):
    context = {
        "form": PostForm()
    }
    return render(request, "blog/create_post.html", context)

demo/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import StudentForm
from .models import Student


def index(request):
    queryset = Student.objects.all()
    context = {'students': queryset}
    template_name = 'demo/index.html'
    return render(request, template_name, context)


def create(request):
    if request.method == 'GET':
        form = StudentForm()
    elif request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("demo:index")
    context = {
        'form': form,
        'title': 'Create student'
    }
    template_name = "demo/create.html"
    return render(request, template_name, context)


def edit(request, pk):
    # try:
    #     student = Student.objects.get(pk=pk)
    # except:
    #     return HttpResponse("404 Not found", status=404)
    student = get_object_or_404(Student, pk=pk)
    if request.method == 'GET':
        form = StudentForm(instance=student)
    elif request.method == 'POST':
        form = StudentForm(instance=student, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('demo:edit', pk)
    template_name = 'demo/create.html'
    context = {'form': form, 'title': 'Edit student'}
    return render(request, template_name, context)


def details(request, pk):
    queryset = get_object_or_404(Student, pk=pk)  # Student.objects.get(pk=pk)
    context = {'student': queryset}
    return render(request, 'demo/details.html', context)


def delete(request, pk):
    student = get_object_or_404(Student, pk=pk) # Student.objects.get(pk=pk)
    student.delete()
    return redirect("demo:index")

blog/templates/blog/create_post.html
{% extends 'blog/main.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="page-header">
            Create post
        </h1>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary" />
        </form>

    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/main.html' %}
{% block content %}
    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <h1 class="page-header">
            Page Heading
            <small>Secondary Text</small>
        </h1>

        <!-- First Blog Post -->
        {% for post in posts %}
            <h2>
                <a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a>
            </h2>
            <p class="lead">
                by <a href="{% url 'blog:index' %}">Start Bootstrap</a>
            </p>
            <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.created|date:'M d, Y' }}
                at {{ post.created|time:'HH:mm' }}</p>
            <hr>
            <img class="img-responsive" src="http://via.placeholder.com/900x300" alt="">
            <hr>
            <p>{{ post.content }}</p>
            <a class="btn btn-primary" href="{% url 'blog:post' post.pk %}">Read More <span
                    class="glyphicon glyphicon-chevron-right"></span></a>

            <hr>
        {% endfor %}

        <!-- Pager -->
        <ul class="pager">
            <li class="previous">
                <a href="#">&larr; Older</a>
            </li>
            <li class="next">
                <a href="#">Newer &rarr;</a>
            </li>
        </ul>

    </div>
{% endblock %}

blog/templates/blog/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'blog:create' %}">Create post</a>
                    </li>
                    <li class="navbar-right">
                        <a href="/admin">Admin</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            {% block content %}{% endblock %}

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <form class="input-group">
                        <input type="text" name="q" class="form-control" value="{{ q }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </form>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

blog/templates/blog/post.html
{% extends 'blog/main.html' %}

{% block content %}
    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
        <h1>Blog Post Title</h1>

        <!-- Author -->
        <p class="lead">
            by <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-responsive" src="http://via.placeholder.com/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error
            quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum
            minus inventore?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste
            ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus,
            voluptatibus.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius
            illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim,
            iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat
            totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam
            tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui,
            necessitatibus, est!</p>

        <hr>

        <!-- Blog Comments -->

        <!-- Comments Form -->
        <div class="well">
            <h4>Leave a Comment:</h4>
            <form role="form">
                <div class="form-group">
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

        <hr>

        <!-- Posted Comments -->

        <!-- Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://via.placeholder.com/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Start Bootstrap
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras
                purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
                fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>

        <!-- Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://via.placeholder.com/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Start Bootstrap
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras
                purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
                fringilla. Donec lacinia congue felis in faucibus.
                <!-- Nested Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://via.placeholder.com/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Nested Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
                        commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum
                        nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>
                <!-- End Nested Comment -->
            </div>
        </div>

    </div>
{% endblock %}

demo/templates/demo/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div>
    <a href="{% url 'demo:index' %}">Home page</a>
</div>
<h1>{{ title }}</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" />
</form>
</body>
</html>

demo/templates/demo/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div>
    <a href="{% url 'demo:index' %}">Home page</a>
</div>

<div>
    <h2>Student details</h2>
    <div>Id: {{ student.pk }}</div>
    <div>First Name: {{ student.first_name }}</div>
    <div>Last Name: {{ student.last_name }}</div>
    <div>Birth Date: {{ student.birth_of_date }}</div>
    <div>Created: {{ student.created }}</div>
    <div>Updated: {{ student.updated }}</div>
    <div>
        <h3>Courses</h3>
        <ul>
            {% for course in student.courses.all %}
                <li>{{ course.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>

</body>
</html>

demo/templates/demo/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div>
    <a href="{% url 'demo:create' %}">Create</a>
</div>

<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {% for student in students %}
        <tr>
            <td>{{ student.id }}</td>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>
                <a href="{% url 'demo:details' student.id %}">Details</a>
                | <a href="{% url 'demo:edit' student.id %}">Edit</a>
                | <a href="{% url 'demo:delete' student.id %}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

</body>
</html>